function createfigure(YMatrix1, EMatrix1, Y1, Y2, E1, YMatrix2, EMatrix2, xvector1, ymatrix3, XMatrix1, YMatrix4, EMatrix3, YData1, XData1, X1, YMatrix5, YData2, YData3)
%CREATEFIGURE(YMATRIX1, EMATRIX1, Y1, Y2, E1, YMATRIX2, EMATRIX2, XVECTOR1, YMATRIX3, XMATRIX1, YMATRIX4, EMATRIX3, YDATA1, XDATA1, X1, YMATRIX5, YDATA2, YDATA3)
%  YMATRIX1:  errorbar y matrix
%  EMATRIX1:  errorbar e matrix
%  Y1:  vector of y data
%  Y2:  errorbar y
%  E1:  errorbar e
%  YMATRIX2:  errorbar y matrix
%  EMATRIX2:  errorbar e matrix
%  XVECTOR1:  bar xvector
%  YMATRIX3:  bar matrix data
%  XMATRIX1:  errorbar x matrix
%  YMATRIX4:  errorbar y matrix
%  EMATRIX3:  errorbar e matrix
%  YDATA1:  patch ydata
%  XDATA1:  patch xdata
%  X1:  vector of x data
%  YMATRIX5:  matrix of y data
%  YDATA2:  patch ydata
%  YDATA3:  patch ydata

%  Auto-generated by MATLAB on 08-Jan-2018 09:17:03

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'Position',[0.05 0.3 0.4 0.2]);
hold(axes1,'on');

% Create multiple error bars using matrix input to errorbar
errorbar1 = errorbar(YMatrix1,EMatrix1,'Color',[0 0 0]);
set(errorbar1(1),'Marker','v');
set(errorbar1(2),'Marker','o');

% Create plot
plot(Y1,'Parent',axes1,'Color',[0 0 0]);

% Create xlabel
xlabel('TrialNo');

% Create ylabel
ylabel('Raw Alpha Power(\muV^2)');

% Create axes
axes2 = axes('Parent',figure1,'Position',[0.05 0.05 0.4 0.2]);
hold(axes2,'on');

% Create errorbar
errorbar(Y2,E1,'Parent',axes2,'Marker','v','Color',[1 0 0]);

% Create multiple error bars using matrix input to errorbar
errorbar2 = errorbar(YMatrix2,EMatrix2,'Marker','v');
set(errorbar2(1),'Color',[0 0 1]);
set(errorbar2(2),'Color',[0 1 0]);

% Create xlabel
xlabel('TrialNo');

% Create ylabel
ylabel('\DeltaPower(dB)');

% Create axes
axes3 = axes('Parent',figure1,'Position',[0.55 0.05 0.4 0.2]);
hold(axes3,'on');

% Create multiple lines using matrix input to bar
bar1 = bar(xvector1,ymatrix3,'Parent',axes3);
set(bar1(3),'FaceColor',[1 0 0]);
set(bar1(2),'FaceColor',[0 1 0]);
set(bar1(1),'FaceColor',[0 0 1]);

% Create multiple error bars using matrix input to errorbar
errorbar3 = errorbar(XMatrix1,YMatrix4,EMatrix3);
set(errorbar3(1),'Color',[0 0 1]);
set(errorbar3(2),'Color',[0 1 0]);
set(errorbar3(3),'Color',[1 0 0]);

% Create xlabel
xlabel('TrialTypes');

% Create ylabel
ylabel('\DeltaPower(dB)');

% Set the remaining axes properties
set(axes3,'XTick',[1 2 3],'XTickLabel',{'Valid','Invalid','Constant'});
% Create axes
axes4 = axes('Parent',figure1,'Position',[0.55 0.3 0.4 0.2]);
hold(axes4,'on');

% Create patch
patch('Parent',axes4,'YData',YData1,'XData',XData1,'FaceAlpha',0.15,...
    'FaceColor',[1 0 0],...
    'EdgeColor','none',...
    'CData',xvector1);

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix5,'Parent',axes4);
set(plot1(1),'Color',[1 0.55 0.55]);
set(plot1(2),'Color',[1 0.55 0.55]);
set(plot1(3),'Color',[1 0 0]);
set(plot1(4),'Color',[0.55 1 0.55]);
set(plot1(5),'Color',[0.55 1 0.55]);
set(plot1(6),'Color',[0 1 0]);
set(plot1(7),'Color',[0.55 0.55 1]);
set(plot1(8),'Color',[0.55 0.55 1]);
set(plot1(9),'Color',[0 0 1]);

% Create patch
patch('Parent',axes4,'YData',YData2,'XData',XData1,'FaceAlpha',0.15,...
    'FaceColor',[0 1 0],...
    'EdgeColor','none',...
    'CData',xvector1);

% Create patch
patch('Parent',axes4,'YData',YData3,'XData',XData1,'FaceAlpha',0.15,...
    'FaceColor',[0 0 1],...
    'EdgeColor','none',...
    'CData',xvector1);

% Create xlabel
xlabel('Time(sec)');

% Create ylabel
ylabel('\DeltaPower(dB)');

