subjectNames = {'ABA','AJ','DB','DD','HS',...
                'SB','SG','SS','SSH','SKS', ...
                'KNB','SSA','SHG','MP','MJR',...
                'ARC','TBR','BPP','SL','PK',...
                'PB','PM','SKH','AD'}';

numSubjects=length(subjectNames); 
for i=1:numSubjects
    disp(i);
    figure(i);    
    biofeedbackFigure1(subjectNames{i},'');
end